### ISSUE TITLE
the running time of  multiple threads in reconstruction and DD (Dynamic Definition) query algorithms

### ISSUE THREAD

**Issue by hang-dev** [Qiskit/qiskit-addon-cutting#366]
_Here is the relevant configuration of my computer_
**OS:** Windows11
**Python Version:** 3.9.1
**CPU:** 12th Gen Inter(R) Core(TM) i9-12900HX 2.30G HZ
**RAM:** 16GB
I'm having some problems with the toolkit.
1. When I try to cut an 8 qubit circuit into 4 subcircuits with a maximum of 3 qubits, the reconstruction of the circuit results in multiple threads running slower than 1 thread
![d680ab54d4436f252daa7c6f0374185](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/assets/51280198/b269a2fa-7ec4-4b69-81e3-14d296a5c9f7)
what is the reason for this? and if  use this toolkit to cut a large-scale circuit, how to deal with the problem of long reconstruction times?

2. What'more,  I see that the  paper called 'CutQC: Using Small Quantum Computers for Large Quantum
Circuit Evaluations'mentioned that there is a **DD(Dynamic Definition) query algorithm**, but it seems that I did not find this algorithm in this toolkit, may be I did not find the interface,  could you tell me how to use this method?

**Comment by caleb-johnson** [comment]
Although cutQC is a legacy tool in this repository, dynamic definition will be added in #285 .

As for these run-times, the problem may not be large enough for you to see an advantage in multi-threading. Do the runtimes behave like this for larger cutting problems?

**Comment by 15565586691** [comment]
Thank you very much for your answer, it's very helpful!

**Comment by garrison** [comment]
Closing all CutQC issues now that it has been removed.
