### ISSUE TITLE
How to use circuit-knitting-toolbox to cut circuits that are not fully connected

### ISSUE THREAD

**Issue by hang-dev** [Qiskit/qiskit-addon-cutting#450]
### **I'm trying to use the circuit-knitting-toolbox to cut a circuit that is not fully connected, but I'm having some problems cutting this circuit.**

_This is the circuit I want to cut_
![48465030d07ab3031eb07173806c659](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/assets/51280198/51374362-0ebd-4107-ac55-97ae05e34516)
_Here are some of the conditions I've set up for the subcircuits_
```python
cuts = cut_circuit_wires(
    circuit = test_circuit,
    method="automatic",
    max_subcircuit_width=5,
    max_cuts=5,
    num_subcircuits=[i for i in range(test_circuit.num_qubits)],
)
``` 
_But something went wrong._
![39e0563a1c0e75f71a0cc1107121256](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/assets/51280198/736d99e0-3647-4bbb-8a03-335499a6c444)

**What is the cause of this and how can I fix it?**

**Comment by caleb-johnson** [comment]
Hi @hang-dev , we have been seeing several different problems with cutqc. It is legacy software, and we are trying to migrate users to the [newer wire cutting functionality](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/main/docs/circuit_cutting/how-tos/how_to_specify_cut_wires.ipynb).

We also have an implementation of an automat cut-finder which supports both gates and wire cuts in a branch [here](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/tree/LO-circuit-cuts-optimizer), which should be available in the upcoming release.

We'd like to know whether this new package suits your needs.

**Comment by garrison** [comment]
Closing all CutQC issues now that it has been removed.
