### ISSUE TITLE
Ensure CKT docs link redirects to CCT docs page

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit/qiskit-addon-cutting#604]

**Comment by garrison** [comment]
From https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository:
>If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, **we don't redirect GitHub Pages associated with the repository.**

There is a possible workaround at https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7.

**Comment by garrison** [comment]
Done at https://github.com/Qiskit-Extensions/qiskit-extensions.github.io/pull/2.
