### ISSUE TITLE
Random generated circuit cannot be cut

### ISSUE THREAD

**Issue by hang-dev** [Qiskit/qiskit-addon-cutting#656]
I randomly generated a 10-bit quantum circuit with a depth of 88 and a number of two-qubit gates of 49, However, the cutting method cannot be found using the mip cutting searcher，What is the reason for this？
Here is my qasm file and  code
[random_qasm.txt](https://github.com/user-attachments/files/16610297/random_qasm.txt)
`cuts = cut_circuit_wires(
    circuit=circuit,
    method="automatic",
    max_subcircuit_width=9,
    max_cuts=100,
    num_subcircuits=[i for i in range(2, 10)],
)`
The error message is：
![b977eec892083a3fe27ef478699f2d5](https://github.com/user-attachments/assets/8b57b383-db6d-4afc-81d5-cac72f0972e6)

**Comment by hang-dev** [comment]
This is the figure of circuit
![image](https://github.com/user-attachments/assets/18919336-6d57-4f93-ac8e-04f4f322a68d)

**Comment by garrison** [comment]
Cutqc is deprecated and no longer supported.  Please use the new cut finder introduced with the 0.7 release series.

**Comment by garrison** [comment]
Closing all CutQC issues now that it has been removed.
